### ISSUE TITLE
关于 getEncryptPasswd的计算方式

### ISSUE THREAD

**Issue by hexsum** [aironefly/LightQQ#1]
smartqq使用的并不是webqq的多重md5加密，也可以通过getEncryptPasswd计算的结果正常登录吗？

**Comment by feitang0** [comment]
之前使用webqq的多重MD5加密是可以登录的，大概在2015年年初就不可以了，现在可以使用二维码登录。

**Comment by hexsum** [comment]
soga～我就觉得奇怪呢，新版本使用的是rsa+tea+base64算法 不过是js的代码，需要自己再转成c++的，有些麻烦，二维码登陆这个我参考下，也添加到自己的项目里
